# Generated by Django 3.2.9 on 2022-02-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_dop', models.CharField(max_length=45, unique=True, verbose_name='ВНИМАНИЕ! УЧИТЫВАЕТСЯ ПРИ ИНДЕКСАЦИИ! Отображаемый адрес')),
                ('html_class_name', models.CharField(max_length=50, verbose_name='Имя (english)')),
                ('name', models.CharField(max_length=80, verbose_name='Имя бренда')),
                ('img_logo', models.ImageField(upload_to='', verbose_name='Логотип бренда')),
                ('location', models.CharField(max_length=50, verbose_name='Головной офис (город)')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('foundation', models.PositiveIntegerField(verbose_name='Основание')),
                ('description_short', models.TextField(verbose_name='Краткое описание')),
                ('description_full', models.TextField(verbose_name='Пару слов о бренде')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'db_table': 'BRANDS',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование категории')),
                ('html_class_name', models.CharField(max_length=50, verbose_name='Имя (english)')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
                'db_table': 'CATEGORY',
            },
        ),
        migrations.CreateModel(
            name='FeedFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation', models.FileField(upload_to='presentation/', verbose_name='Файл для загрузки')),
                ('html_class_name', models.CharField(max_length=50, verbose_name='Имя (english)')),
            ],
            options={
                'verbose_name': 'Презентацию',
                'verbose_name_plural': 'Презентации',
                'db_table': 'PRESENTATIONS',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_dop', models.CharField(max_length=45, unique=True, verbose_name='ВНИМАНИЕ! УЧИТЫВАЕТСЯ ПРИ ИНДЕКСАЦИИ! Отображаемый адрес')),
                ('code', models.PositiveIntegerField(verbose_name='Артикул')),
                ('name', models.CharField(max_length=50, verbose_name='Имя продукта')),
                ('specifications', models.TextField(verbose_name='Спецификации (разделять символом (%)')),
                ('description_short', models.TextField(verbose_name='Краткое описание')),
                ('description_full', models.TextField(verbose_name='Описание')),
                ('category', models.ManyToManyField(to='mainapp.Category', verbose_name='Категория')),
                ('download_files', models.ManyToManyField(to='mainapp.FeedFiles', verbose_name='Выберите файлы для скачивания')),
                ('manufacturer', models.ManyToManyField(to='mainapp.Brand', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'PRODUCTS',
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ManyToManyField(to='mainapp.Category', verbose_name='Направления бренда'),
        ),
    ]
