# Generated by Django 3.2.9 on 2022-02-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedfiles',
            name='name',
            field=models.CharField(default='nua', max_length=50, verbose_name='Имя файла'),
            preserve_default=False,
        ),
    ]
