# Generated by Django 3.2.9 on 2022-02-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_feedfiles_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_product',
            field=models.ImageField(default='text', upload_to='images/', verbose_name='Изображение продукта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='img_logo',
            field=models.ImageField(upload_to='images/', verbose_name='Логотип бренда'),
        ),
    ]
