# Generated by Django 3.2.9 on 2022-02-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20220215_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=3434, verbose_name='Стоимость продукта'),
            preserve_default=False,
        ),
    ]
