# Generated by Django 3.2.9 on 2022-04-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_product_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_products', models.ManyToManyField(limit_choices_to={'name': 2}, to='mainapp.Product', verbose_name='Актуальные продукты (ряд из 4х продуктов на главной)')),
            ],
        ),
    ]
