# Generated by Django 3.2.9 on 2022-04-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_mainpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpage',
            options={'verbose_name': 'Главная', 'verbose_name_plural': 'Главная'},
        ),
        migrations.AddField(
            model_name='mainpage',
            name='name',
            field=models.CharField(default=12, max_length=80, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='mainpage',
            table='MAINPAGE',
        ),
    ]
