# Generated by Django 3.2.9 on 2022-04-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20220419_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='actual_products',
            field=models.ManyToManyField(limit_choices_to={'actual_products': 2}, to='mainapp.Product', verbose_name='Актуальные'),
        ),
    ]
