# Generated by Django 3.2.9 on 2022-04-19 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_mainpage_actual_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainPage',
        ),
    ]
