# Generated by Django 3.2.9 on 2022-04-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_delete_mainpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_main_page',
            field=models.BooleanField(default=False, verbose_name='Показывать на "Главной"'),
        ),
    ]
