# Generated by Django 3.2.9 on 2022-04-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20220420_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Настройки')),
                ('advertising', models.TextField(verbose_name='Реклама в шапке')),
                ('phone', models.CharField(max_length=25, unique=True, verbose_name='Телефон компании')),
                ('phone_html', models.IntegerField(default=170)),
                ('adress', models.CharField(max_length=86, verbose_name='Адрес')),
                ('email_sales', models.EmailField(max_length=254, verbose_name='Email (продажи)')),
                ('email_support', models.EmailField(max_length=254, verbose_name='Email (поддержка)')),
            ],
            options={
                'verbose_name': 'Hастройки',
                'verbose_name_plural': 'Hастройки',
                'db_table': 'MAINSETTINGS',
            },
        ),
        migrations.DeleteModel(
            name='MainPageSettings',
        ),
    ]
