# Generated by Django 3.2.9 on 2022-09-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20220420_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_product',
            field=models.BooleanField(default=True, verbose_name='Продукт виден посетителям'),
        ),
    ]
