# Generated by Django 3.2.9 on 2022-09-25 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_product_display_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='display_product',
        ),
    ]
